# config.yaml example
samples:
    SRR5938419: "SRR5938419_Aligned.sortedByCoord.out.bam"
    SRR5938420: "SRR5938420_Aligned.sortedByCoord.out.bam"
    SRR5938421: "SRR5938421_Aligned.sortedByCoord.out.bam"
    SRR5938422: "SRR5938422_Aligned.sortedByCoord.out.bam"
    SRR5938423: "SRR5938423_Aligned.sortedByCoord.out.bam"
    SRR5938424: "SRR5938424_Aligned.sortedByCoord.out.bam"
    SRR5938425: "SRR5938425_Aligned.sortedByCoord.out.bam"
    SRR5938426: "SRR5938426_Aligned.sortedByCoord.out.bam"
    SRR5938427: "SRR5938427_Aligned.sortedByCoord.out.bam"
    SRR5938428: "SRR5938428_Aligned.sortedByCoord.out.bam"
    SRR5938429: "SRR5938429_Aligned.sortedByCoord.out.bam"
    SRR5938430: "SRR5938430_Aligned.sortedByCoord.out.bam"
    SRR5938431: "SRR5938431_Aligned.sortedByCoord.out.bam"
    SRR5938432: "SRR5938432_Aligned.sortedByCoord.out.bam"
    SRR5938433: "SRR5938433_Aligned.sortedByCoord.out.bam"
    SRR5938434: "SRR5938434_Aligned.sortedByCoord.out.bam"
    SRR5938435: "SRR5938435_Aligned.sortedByCoord.out.bam"
    SRR5938436: "SRR5938436_Aligned.sortedByCoord.out.bam"
    SRR5938437: "SRR5938437_Aligned.sortedByCoord.out.bam"
    SRR5938438: "SRR5938438_Aligned.sortedByCoord.out.bam"
    SRR5938439: "SRR5938439_Aligned.sortedByCoord.out.bam"
    SRR5938440: "SRR5938440_Aligned.sortedByCoord.out.bam"
    SRR5938441: "SRR5938441_Aligned.sortedByCoord.out.bam"
    SRR5938442: "SRR5938442_Aligned.sortedByCoord.out.bam"
    SRR5938443: "SRR5938443_Aligned.sortedByCoord.out.bam"
    SRR5938444: "SRR5938444_Aligned.sortedByCoord.out.bam"
    SRR5938445: "SRR5938445_Aligned.sortedByCoord.out.bam"
    SRR5938446: "SRR5938446_Aligned.sortedByCoord.out.bam"
    SRR5938447: "SRR5938447_Aligned.sortedByCoord.out.bam"
    SRR5938448: "SRR5938448_Aligned.sortedByCoord.out.bam"
    SRR5938449: "SRR5938449_Aligned.sortedByCoord.out.bam"
    SRR5938450: "SRR5938450_Aligned.sortedByCoord.out.bam"
    SRR5938451: "SRR5938451_Aligned.sortedByCoord.out.bam"
    SRR5938452: "SRR5938452_Aligned.sortedByCoord.out.bam"
    SRR5938453: "SRR5938453_Aligned.sortedByCoord.out.bam"
    SRR5938454: "SRR5938454_Aligned.sortedByCoord.out.bam"
    SRR5938455: "SRR5938455_Aligned.sortedByCoord.out.bam"
    SRR5938456: "SRR5938456_Aligned.sortedByCoord.out.bam"
    SRR5938457: "SRR5938457_Aligned.sortedByCoord.out.bam"
    SRR5938458: "SRR5938458_Aligned.sortedByCoord.out.bam"
    SRR5938459: "SRR5938459_Aligned.sortedByCoord.out.bam"
    SRR5938460: "SRR5938460_Aligned.sortedByCoord.out.bam"
    SRR5938461: "SRR5938461_Aligned.sortedByCoord.out.bam"
    SRR5938462: "SRR5938462_Aligned.sortedByCoord.out.bam"
    SRR5938463: "SRR5938463_Aligned.sortedByCoord.out.bam"
    SRR5938464: "SRR5938464_Aligned.sortedByCoord.out.bam"
    SRR5938465: "SRR5938465_Aligned.sortedByCoord.out.bam"
    SRR5938466: "SRR5938466_Aligned.sortedByCoord.out.bam"
    SRR5938467: "SRR5938467_Aligned.sortedByCoord.out.bam"
    SRR5938468: "SRR5938468_Aligned.sortedByCoord.out.bam"
    SRR5938469: "SRR5938469_Aligned.sortedByCoord.out.bam"
    SRR5938470: "SRR5938470_Aligned.sortedByCoord.out.bam"

refFasta: "/home/samlee/GRCh38rel90/Homo_sapiens.GRCh38.dna.primary_assembly.fa"

OpossumDir: "/home/samlee/bin/Opossum"

bamDir: "/home/samlee/asd-sex-effects/gse102741-star"